/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import DTOs.salida.DetalleComandaViejaDTO;
import DTOs.salida.ProductoResumenDTO;


/**
 *
 * @author norma
 */
public class PanelProductosComanda extends javax.swing.JPanel {

    public PanelProductosComanda(ProductoResumenDTO producto, DetalleComandaViejaDTO detalleComanda) {
        initComponents();

        lblNombreProducto.setText(producto.getNombre());
        lblPrecioProducto.setText(String.format("$%.2f", producto.getPrecio()));
        lblDetalle.setText(detalleComanda.getComentario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDetalle = new javax.swing.JLabel();
        lblDetalles = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblSignoPrecio = new javax.swing.JLabel();
        lblPrecioProducto = new javax.swing.JLabel();

        lblDetalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDetalle.setText("Detalle");

        lblDetalles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDetalles.setText("Detalles:");

        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreProducto.setText("Nombre Producto");

        lblSignoPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoPrecio.setText("$");

        lblPrecioProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecioProducto.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblNombreProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(lblSignoPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreProducto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPrecioProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSignoPrecio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetalles)
                    .addComponent(lblDetalle))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblSignoPrecio;
    // End of variables declaration//GEN-END:variables
}
