/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

/**
 *
 * @author norma
 */
public class PanelClienteFrecuente extends javax.swing.JPanel {

    /**
     * Creates new form PanelClienteFrecuente
     */
    public PanelClienteFrecuente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreClienteFrecuente = new javax.swing.JLabel();
        lblNumeroVisitas = new javax.swing.JLabel();
        lblPuntosFidelidad = new javax.swing.JLabel();
        lblTotalGastado = new javax.swing.JLabel();
        lblFechaUltimaComanda = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        lblNombreClienteFrecuente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreClienteFrecuente.setText("Nombre Cliente Frecuente");

        lblNumeroVisitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumeroVisitas.setText("Número de visitas:");

        lblPuntosFidelidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPuntosFidelidad.setText("Puntos de fidelidad:");

        lblTotalGastado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalGastado.setText("Total gastado:");

        lblFechaUltimaComanda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaUltimaComanda.setText("Fecha de última comanda: ");

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setText("100");

        lblPuntos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPuntos.setText("100");

        lblTotal1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal1.setText("100");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalGastado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal1))
                    .addComponent(lblNombreClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeroVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPuntosFidelidad, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaUltimaComanda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNombreClienteFrecuente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroVisitas)
                    .addComponent(lblNumero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalGastado)
                    .addComponent(lblTotal1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuntosFidelidad)
                    .addComponent(lblPuntos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaUltimaComanda)
                    .addComponent(lblFecha))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaUltimaComanda;
    private javax.swing.JLabel lblNombreClienteFrecuente;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroVisitas;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblPuntosFidelidad;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotalGastado;
    // End of variables declaration//GEN-END:variables
}
