/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

/**
 *
 * @author norma
 */
public class PanelComanda extends javax.swing.JPanel {

    /**
     * Creates new form PanelComanda
     */
    public PanelComanda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        lblFolio1 = new javax.swing.JLabel();
        lblFolioComanda1 = new javax.swing.JLabel();
        lblFechaComanda1 = new javax.swing.JLabel();
        lblCliente1 = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblProductos = new javax.swing.JLabel();
        pnlComandaProductos = new javax.swing.JPanel();
        pnlPrecioTotal = new javax.swing.JPanel();
        btnSignoPrecio = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();

        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreCliente.setText("Sin registrar");
        pnlBotones.add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 122, 258, -1));

        lblFolio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFolio1.setText("Folio:");
        pnlBotones.add(lblFolio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 28, 59, -1));

        lblFolioComanda1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFolioComanda1.setText("OB-2025-03-28-1");
        pnlBotones.add(lblFolioComanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 27, 159, -1));

        lblFechaComanda1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaComanda1.setText("2025-03-28 2:30:20");
        pnlBotones.add(lblFechaComanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 74, 152, -1));

        lblCliente1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCliente1.setText("Cliente:");
        pnlBotones.add(lblCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 122, 55, -1));

        btnTerminar.setBackground(new java.awt.Color(123, 191, 112));
        btnTerminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 115, -1, -1));

        btnEditar1.setBackground(new java.awt.Color(153, 153, 153));
        btnEditar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        pnlBotones.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 24, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 24, -1, -1));

        lblProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductos.setText("Productos:");
        pnlBotones.add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 165, 91, -1));

        javax.swing.GroupLayout pnlComandaProductosLayout = new javax.swing.GroupLayout(pnlComandaProductos);
        pnlComandaProductos.setLayout(pnlComandaProductosLayout);
        pnlComandaProductosLayout.setHorizontalGroup(
            pnlComandaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlComandaProductosLayout.setVerticalGroup(
            pnlComandaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        btnSignoPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignoPrecio.setText("$");

        lblPrecioTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecioTotal.setText("100");

        javax.swing.GroupLayout pnlPrecioTotalLayout = new javax.swing.GroupLayout(pnlPrecioTotal);
        pnlPrecioTotal.setLayout(pnlPrecioTotalLayout);
        pnlPrecioTotalLayout.setHorizontalGroup(
            pnlPrecioTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrecioTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignoPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPrecioTotalLayout.setVerticalGroup(
            pnlPrecioTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrecioTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrecioTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignoPrecio))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(636, 636, 636)
                .addComponent(pnlComandaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlPrecioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlComandaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JLabel btnSignoPrecio;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblFechaComanda1;
    private javax.swing.JLabel lblFolio1;
    private javax.swing.JLabel lblFolioComanda1;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlComandaProductos;
    private javax.swing.JPanel pnlPrecioTotal;
    // End of variables declaration//GEN-END:variables
}
