package pantallas;

import DTOs.salida.ClienteViejoDTO;
import DTOs.salida.ProductoResumenDTO;
import control.ControlNavegacion;
import entidades.enums.TipoProducto;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author pablo
 */
public class PantallaTablaClientes extends javax.swing.JFrame {

    List<ClienteViejoDTO> clientes;
    private JButton button;
    private String label;
    private boolean isPushed;
    private int selectedRow;

    /**
     * Creates new form PantallaTablaClientes
     *
     * @param clientes
     */
    public PantallaTablaClientes(List<ClienteViejoDTO> clientes) {
        initComponents();
        int puntosFidelidad = 0;
        JButton boton = new JButton();
        this.clientes = clientes;
//        for (TipoProducto tipo : TipoProducto.values()) {
//            cmbCategoria.addItem(tipo.toString());
//        }
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        for (ClienteViejoDTO cliente : clientes) {
            Object[] fila = {
                cliente.getId(),
                cliente.getNombres(),
                cliente.getTelefono(),
                cliente.getCorreo(),
                cliente.getFechaRegistro(),
                puntosFidelidad,};
            modelo.addRow(fila);
        }
        jTable1.getColumnModel().getColumn(6).setCellRenderer(new BotonesRender());
        jTable1.getColumnModel().getColumn(6).setCellEditor(new ButtonEditor(new JCheckBox()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        sepArriba = new javax.swing.JSeparator();
        chkNombreProducto2 = new javax.swing.JCheckBox();
        txtNombreProducto = new javax.swing.JTextField();
        txtNombreProducto3 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        sepAbajo1 = new javax.swing.JSeparator();
        lblTitulo1 = new javax.swing.JLabel();
        sepArriba1 = new javax.swing.JSeparator();
        btnVolverAtras = new javax.swing.JButton();
        chkCorreo = new javax.swing.JCheckBox();
        chkNombre = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        chkTelefono = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sepAbajo3 = new javax.swing.JSeparator();
        sepAbajo2 = new javax.swing.JSeparator();
        btnFiltrar = new javax.swing.JButton();
        btnSinComanda = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Productos");
        lblTitulo.setToolTipText("");

        chkNombreProducto2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkNombreProducto2.setText("Nombre producto");
        chkNombreProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNombreProducto2ActionPerformed(evt);
            }
        });

        txtNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreProducto.setEnabled(false);
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });

        txtNombreProducto3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreProducto3.setEnabled(false);
        txtNombreProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProducto3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo1.setText("Clientes frecuentes");
        lblTitulo1.setToolTipText("");

        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolverAtras.setText("<---");
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });

        chkCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkCorreo.setText("Correo");
        chkCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCorreoActionPerformed(evt);
            }
        });

        chkNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkNombre.setText("Nombre");
        chkNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNombreActionPerformed(evt);
            }
        });

        chkTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTelefono.setText("Telefono");
        chkTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTelefonoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono", "Correo", "Fecha registro", "Puntos fidelidad", "Asignar comanda"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnFiltrar.setBackground(new java.awt.Color(170, 200, 100));
        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnSinComanda.setBackground(new java.awt.Color(170, 200, 100));
        btnSinComanda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSinComanda.setText("Continuar sin comanda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepArriba1)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCorreo)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 105, Short.MAX_VALUE))
            .addComponent(sepAbajo2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo1)
                            .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSinComanda)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sepAbajo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepArriba1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepAbajo2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSinComanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 300, Short.MAX_VALUE)
                    .addComponent(sepAbajo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 301, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkNombreProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNombreProducto2ActionPerformed

    }//GEN-LAST:event_chkNombreProducto2ActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed

    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtNombreProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProducto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProducto3ActionPerformed

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        ControlNavegacion.mostrarTipoCliente();
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void chkCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCorreoActionPerformed
        boolean estado = chkCorreo.isSelected();
        txtNombreProducto.setEnabled(estado);
    }//GEN-LAST:event_chkCorreoActionPerformed

    private void chkNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNombreActionPerformed
        boolean estado = chkNombre.isSelected();
        txtNombreProducto.setEnabled(estado);
    }//GEN-LAST:event_chkNombreActionPerformed

    private void chkTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTelefonoActionPerformed
        boolean estado = chkTelefono.isSelected();
        txtNombreProducto.setEnabled(estado);
    }//GEN-LAST:event_chkTelefonoActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String filtroClienteNombre = chkNombre.isSelected() ? txtNombre.getText().strip() : "";
        String filtroClienteCorreo = chkCorreo.isSelected() ? txtCorreo.getText().strip() : "";
        String filtroClienteTelefono = chkTelefono.isSelected() ? txtTelefono.getText().strip() : "";
        ControlNavegacion.mostrarPantallaTablaCliente(filtroClienteNombre, filtroClienteCorreo, filtroClienteTelefono);
        this.dispose();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnSinComanda;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JCheckBox chkCorreo;
    private javax.swing.JCheckBox chkNombre;
    private javax.swing.JCheckBox chkNombreProducto2;
    private javax.swing.JCheckBox chkTelefono;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JSeparator sepAbajo1;
    private javax.swing.JSeparator sepAbajo2;
    private javax.swing.JSeparator sepAbajo3;
    private javax.swing.JSeparator sepArriba;
    private javax.swing.JSeparator sepArriba1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNombreProducto3;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    class ButtonEditor extends DefaultCellEditor {

        private JButton button;
        private String label;
        private boolean isPushed;
        private int selectedRow;

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);

            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (isPushed) {
                        ClienteViejoDTO cliente = clientes.get(selectedRow);
                        JOptionPane.showMessageDialog(null, "Fila de perfil de " + cliente.getNombres());
                    }
                    isPushed = false;
                    fireEditingStopped();
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            label = (value == null) ? "Agregar" : value.toString();
            button.setText(label);
            isPushed = true;
            selectedRow = row; // Guardamos la fila seleccionada
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }
    }

}
