/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import control.ControlNavegacion;

/**
 *
 * @author pablo
 */
public class PantallaRegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaaRegistroCliente
     */
    public PantallaRegistroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sepAbajo = new javax.swing.JSeparator();
        lblSubtitulo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        sepArriba1 = new javax.swing.JSeparator();
        sepAbajo1 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JButton();
        btnConfirmarRegistro = new javax.swing.JButton();
        EspacioTextoNombre = new javax.swing.JTextField();
        lblSubtitulo1 = new javax.swing.JLabel();
        lblSubtitulo2 = new javax.swing.JLabel();
        EspacioTextoNombre1 = new javax.swing.JTextField();
        lblSubtitulo3 = new javax.swing.JLabel();
        EspacioTextoNombre2 = new javax.swing.JTextField();
        lblSubtitulo4 = new javax.swing.JLabel();
        EspacioTextoNombre3 = new javax.swing.JTextField();
        lblSubtitulo5 = new javax.swing.JLabel();
        EspacioTextoNombre4 = new javax.swing.JTextField();

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo.setText("¿Qué deseas hacer?");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo1.setText("Registro de cliente");

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setText("<--");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConfirmarRegistro.setBackground(new java.awt.Color(0, 131, 125));
        btnConfirmarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmarRegistro.setText("Confirmar registro");
        btnConfirmarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRegistroActionPerformed(evt);
            }
        });

        EspacioTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoNombreActionPerformed(evt);
            }
        });

        lblSubtitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo1.setText("Nombre(s)");

        lblSubtitulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo2.setText("Apellido paterno");

        EspacioTextoNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoNombre1ActionPerformed(evt);
            }
        });

        lblSubtitulo3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo3.setText("Apellido materno");

        EspacioTextoNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoNombre2ActionPerformed(evt);
            }
        });

        lblSubtitulo4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo4.setText("Número de teléfono");

        EspacioTextoNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoNombre3ActionPerformed(evt);
            }
        });

        lblSubtitulo5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo5.setText("Correo electrónico");

        EspacioTextoNombre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoNombre4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepArriba1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(sepAbajo1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo5)
                    .addComponent(EspacioTextoNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo4)
                    .addComponent(EspacioTextoNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo3)
                    .addComponent(EspacioTextoNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo2)
                    .addComponent(EspacioTextoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo1)
                    .addComponent(EspacioTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepArriba1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo1)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo2)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo3)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo4)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo5)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(sepAbajo1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlNavegacion.mostrarPantallaInicioSesion();
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRegistroActionPerformed

    }//GEN-LAST:event_btnConfirmarRegistroActionPerformed

    private void EspacioTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoNombreActionPerformed

    private void EspacioTextoNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoNombre1ActionPerformed

    private void EspacioTextoNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoNombre2ActionPerformed

    private void EspacioTextoNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoNombre3ActionPerformed

    private void EspacioTextoNombre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoNombre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoNombre4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EspacioTextoNombre;
    private javax.swing.JTextField EspacioTextoNombre1;
    private javax.swing.JTextField EspacioTextoNombre2;
    private javax.swing.JTextField EspacioTextoNombre3;
    private javax.swing.JTextField EspacioTextoNombre4;
    private javax.swing.JButton btnConfirmarRegistro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtitulo1;
    private javax.swing.JLabel lblSubtitulo2;
    private javax.swing.JLabel lblSubtitulo3;
    private javax.swing.JLabel lblSubtitulo4;
    private javax.swing.JLabel lblSubtitulo5;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JSeparator sepAbajo;
    private javax.swing.JSeparator sepAbajo1;
    private javax.swing.JSeparator sepArriba1;
    // End of variables declaration//GEN-END:variables
}
