/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import control.ControlNavegacion;
import control.enums.ModoMenu;
import control.enums.ModoTablaProductos;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author pablo
 */
public class PantallaMenuReporte extends javax.swing.JFrame {

    private JButton btnRegresar;
    private final int DIMENSION_BOTON_X = 150;
    private final int DIMENSION_BOTON_Y = 50;
    private final JButton BTN_REPORTE_CLIENTE = new PlantillaBotonMenuOpciones("Reporte de clientes frecuentes", "#6372B0");
    private final JButton BTN_REPORTE_COMANDA = new PlantillaBotonMenuOpciones("Reporte de comandas", "#6372B0");

    /**
     * Creates new form PantallaMenuReporte
     */
    public PantallaMenuReporte() {
        initComponents();
        iniciarPanel();
    }

    private void iniciarPanel() {
        pnlBotones.setLayout(new FlowLayout(FlowLayout.CENTER, 50, 50));
        BTN_REPORTE_CLIENTE.setFont(new Font("Segoe UI", Font.BOLD, 30));
        BTN_REPORTE_COMANDA.setFont(new Font("Segoe UI", Font.BOLD, 30));
        BTN_REPORTE_CLIENTE.setPreferredSize(new Dimension(230, 300));
        BTN_REPORTE_COMANDA.setPreferredSize(new Dimension(230, 300));
        pnlBotones.add(BTN_REPORTE_CLIENTE);
        pnlBotones.add(BTN_REPORTE_COMANDA);

        BTN_REPORTE_CLIENTE.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                dispose();
            }
        });

        BTN_REPORTE_COMANDA.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnRegistrarProducto = new javax.swing.JButton();
        javax.swing.JButton btnVolveR = new javax.swing.JButton();
        sepAbajo = new javax.swing.JSeparator();
        lblTitulo1 = new javax.swing.JLabel();
        sepArriba = new javax.swing.JSeparator();
        pnlBotones = new javax.swing.JPanel();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Menú producto");

        btnRegistrarProducto.setBackground(new java.awt.Color(135, 174, 206));
        btnRegistrarProducto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrarProducto.setText("<html><center>Registrar nuevo producto</center></html>");
        btnRegistrarProducto.setToolTipText("");
        btnRegistrarProducto.setPreferredSize(new java.awt.Dimension(250, 250));
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolveR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolveR.setText("<---");
        btnVolveR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolveRActionPerformed(evt);
            }
        });

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo1.setText("Menú reportes");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepAbajo)
            .addComponent(sepArriba)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolveR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo1))
                .addContainerGap(547, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 460, Short.MAX_VALUE)
                .addComponent(sepAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolveR, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(113, 113, 113)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolveRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolveRActionPerformed
        ControlNavegacion.mostrarPantallaMenuOpciones(ModoMenu.ADMINISTRADOR);
        this.dispose();
    }//GEN-LAST:event_btnVolveRActionPerformed

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JSeparator sepAbajo;
    private javax.swing.JSeparator sepArriba;
    // End of variables declaration//GEN-END:variables
}
