package pantallas;

import BOs.ClienteBO;
import DTOs.entrada.ClienteNuevoDTO;
import control.ControlNavegacion;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class PantallaRegistroCliente extends javax.swing.JFrame {

    ClienteBO clienteBO = new ClienteBO();
    ControlNavegacion control = new ControlNavegacion();

    /**
     * Creates new form PantallaaRegistroCliente
     */
    public PantallaRegistroCliente() {
        initComponents();
    }

    private void validarRegistro() {
        LocalDate fechaActual = LocalDate.now();

        String Nombres = EspacioTextoNombre.getText();
        String ApellidoP = EspacioTextoApellidoP.getText();
        String ApellidoM = EspacioTextoApellidoM.getText();
        String Telefono = EspacioTextoTelefono.getText();
        String Correo = EspacioTextoCorreo.getText();
        String telefonoEncriptado = Encriptador.encriptarBase64(Telefono);
        String correoEncriptado = Encriptador.encriptarBase64(Correo);

        try {
            if (Nombres.isBlank() || ApellidoP.isBlank() || Telefono.isBlank() || Correo.isBlank()) {
                JOptionPane.showMessageDialog(this, "Error: Falta informacion requerida", "Error", JOptionPane.ERROR_MESSAGE);
            }else {
                ClienteNuevoDTO clienteIngresado = new ClienteNuevoDTO();
                clienteIngresado.setNombres(Nombres);
                clienteIngresado.setApellidoP(ApellidoP);
                clienteIngresado.setApellidoM(ApellidoM);
                clienteIngresado.setTelefono(telefonoEncriptado);
                clienteIngresado.setCorreo(correoEncriptado);
                clienteIngresado.setFechaRegistro(fechaActual);
                
                clienteBO.persistirClienteFrecuente(clienteIngresado);
                JOptionPane.showMessageDialog(this, "Cliente registrado correctamente");
            }
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al procesar el cliente: ",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sepAbajo = new javax.swing.JSeparator();
        lblSubtitulo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        sepArriba1 = new javax.swing.JSeparator();
        sepAbajo1 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JButton();
        btnConfirmarRegistro = new javax.swing.JButton();
        EspacioTextoNombre = new javax.swing.JTextField();
        lblSubtitulo1 = new javax.swing.JLabel();
        lblSubtitulo2 = new javax.swing.JLabel();
        EspacioTextoApellidoP = new javax.swing.JTextField();
        lblSubtitulo3 = new javax.swing.JLabel();
        EspacioTextoApellidoM = new javax.swing.JTextField();
        lblSubtitulo4 = new javax.swing.JLabel();
        EspacioTextoTelefono = new javax.swing.JTextField();
        lblSubtitulo5 = new javax.swing.JLabel();
        EspacioTextoCorreo = new javax.swing.JTextField();

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo.setText("¿Qué deseas hacer?");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo1.setText("Registro de cliente");

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setText("<--");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConfirmarRegistro.setBackground(new java.awt.Color(170, 200, 100));
        btnConfirmarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmarRegistro.setText("Confirmar registro");
        btnConfirmarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRegistroActionPerformed(evt);
            }
        });

        EspacioTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoNombreActionPerformed(evt);
            }
        });

        lblSubtitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo1.setText("Nombre(s)");

        lblSubtitulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo2.setText("Apellido paterno");

        EspacioTextoApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoApellidoPActionPerformed(evt);
            }
        });

        lblSubtitulo3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo3.setText("Apellido materno(opcional)");

        EspacioTextoApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoApellidoMActionPerformed(evt);
            }
        });

        lblSubtitulo4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo4.setText("Número de teléfono");

        EspacioTextoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoTelefonoActionPerformed(evt);
            }
        });

        lblSubtitulo5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubtitulo5.setText("Correo electrónico");

        EspacioTextoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioTextoCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepArriba1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(sepAbajo1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo5)
                    .addComponent(EspacioTextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo4)
                    .addComponent(EspacioTextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo3)
                    .addComponent(EspacioTextoApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo2)
                    .addComponent(EspacioTextoApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo1)
                    .addComponent(EspacioTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepArriba1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo1)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo2)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo3)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo4)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo5)
                .addGap(4, 4, 4)
                .addComponent(EspacioTextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(sepAbajo1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlNavegacion.mostrarPantallaMenuOpciones();
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRegistroActionPerformed
        validarRegistro();
    }//GEN-LAST:event_btnConfirmarRegistroActionPerformed

    private void EspacioTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoNombreActionPerformed

    private void EspacioTextoApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoApellidoPActionPerformed

    private void EspacioTextoApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoApellidoMActionPerformed

    private void EspacioTextoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoTelefonoActionPerformed

    private void EspacioTextoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioTextoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioTextoCorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EspacioTextoApellidoM;
    private javax.swing.JTextField EspacioTextoApellidoP;
    private javax.swing.JTextField EspacioTextoCorreo;
    private javax.swing.JTextField EspacioTextoNombre;
    private javax.swing.JTextField EspacioTextoTelefono;
    private javax.swing.JButton btnConfirmarRegistro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtitulo1;
    private javax.swing.JLabel lblSubtitulo2;
    private javax.swing.JLabel lblSubtitulo3;
    private javax.swing.JLabel lblSubtitulo4;
    private javax.swing.JLabel lblSubtitulo5;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JSeparator sepAbajo;
    private javax.swing.JSeparator sepAbajo1;
    private javax.swing.JSeparator sepArriba1;
    // End of variables declaration//GEN-END:variables
}
